# ===== BOT CONFIG =====

BOT_TOKEN = "8570409684:AAEQBhKv0zMZaEXWcoCUGiJsKRspE5JuleM"
BOT_NAME = "Aquila AI"

# ===== ENGINE SETTINGS =====
CHECK_INTERVAL_SECONDS = 60
ENABLE_NO_SIGNAL_ALERT = False

# ===== TRADING SETTINGS =====
DEFAULT_TIMEFRAME = "1m"
PAIRS = [
    "EURUSD",
    "EURJPY",
    "EURGBP",
    "AUDCAD",
    "USDJPY"
]

LANG = "ar"
